#
# To deploy:
#
# kubectl apply -f scripts/deployment.yml
#
#


#deployment details for loading deakin-library image (book_catalog)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deakin-library
  labels:
    app: deakin-library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deakin-library
  template:
    metadata:
      labels:
        app: deakin-library
    spec:
      containers:
      - name: deakin-library
        image: sit722joeldaniel.azurecr.io/deakin-library:latest
        imagePullPolicy: IfNotPresent 
        env:
        - name: PORT
          value: "4000"
        - name: DATABASE_URL
          value: "postgresql://sit722_task8_2c_user:RTKx1lGv5xFbMnqY8OlLyWFUzPfY9aX7@dpg-cr65263tq21c73b9fqa0-a.singapore-postgres.render.com/sit722_task8_2c"
---
apiVersion: v1
kind: Service
metadata:
  name: deakin-library
spec:
  selector:
    app: deakin-library
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 31000
      targetPort: 4000


---
#deployment details for loading deakin-library image (book_catalog)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deakin-inventory
  labels:
    app: deakin-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deakin-inventory
  template:
    metadata:
      labels:
        app: deakin-inventory
    spec:
      containers:
      - name: deakin-inventory
        image: sit722joeldaniel.azurecr.io/deakin-inventory:latest
        imagePullPolicy: IfNotPresent 
        env:
        - name: PORT
          value: "5000"
        - name: DATABASE_URL
          value: "postgresql://sit722_task8_2c_user:RTKx1lGv5xFbMnqY8OlLyWFUzPfY9aX7@dpg-cr65263tq21c73b9fqa0-a.singapore-postgres.render.com/sit722_task8_2c"
---
apiVersion: v1
kind: Service
metadata:
  name: deakin-inventory
spec:
  selector:
    app: deakin-inventory
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 32000
      targetPort: 5000